### ISSUE TITLE
Update default icons

### ISSUE THREAD

**Issue by jonepatr** [xdy/twodsix-foundryvtt#496]
**Is your feature request related to a problem? Please describe.**
The default icons could be improved. The current "mystery man" does not entirely fit the traveller theme, and giving weapons and items different icons could help distinguishing between them.

**Describe the solution you'd like**
Replace the default icons for actors and items.

**Describe alternatives you've considered**

**Additional context**
Here are some icons that could be used for space ships:
* https://game-icons.net/1x1/delapouite/jet-fighter.html
* https://game-icons.net/1x1/lorc/bubble-field.html
* https://game-icons.net/1x1/delapouite/spaceship.html
* https://game-icons.net/1x1/delapouite/space-shuttle.html

And here are some for actors:
* https://game-icons.net/tags/body.html
* https://game-icons.net/tags/head.html

**Comment by marvin9257** [comment]
What about these? I tried to make them so that they could also work as token icons.  It took me a while to figure out that FVTT really wants the token.img to be a png file.

![person_dark](https://user-images.githubusercontent.com/72580196/121811083-d210b300-cc28-11eb-8e21-6c7c51d83b57.png)
![person_light](https://user-images.githubusercontent.com/72580196/121811085-d2a94980-cc28-11eb-8d55-b31ca0c81635.png)
![spaceship_dark](https://user-images.githubusercontent.com/72580196/121811087-d2a94980-cc28-11eb-8741-22c868488712.png)
![spaceship_light](https://user-images.githubusercontent.com/72580196/121811088-d2a94980-cc28-11eb-8d4c-075053e86a95.png)

**Comment by marvin9257** [comment]
I'm not certain the best location to make these changes, I think it is in the _onCreate() and would look something like this:
```
async _onCreate(data, options, user) {
   let image='';
   switch (this.type) {
        case "traveller":
          await this.createUntrainedSkill();
          image = 'systems/twodsix/assets/icons/imageTraveller.png'
          break;
        case "ship":
          image = 'systems/twodsix/assets/icons/imageShip.png'
          break;
        default:
           break;
    }
    if (image!='') {
        await this.update({
           'img': image,
           'token.img': image
        });
    }
}
```
But maybe there is a better place to do this.

**Comment by marvin9257** [comment]
Ok, what about this one for weapons?  Covers both types melee and more advanced guns.
![saber-and-pistol](https://user-images.githubusercontent.com/72580196/122054869-b1259a80-cdad-11eb-9f41-93083109bc58.png)

**Comment by xdy** [comment]
The change above is in, so closing this issue.
